baseURL: "https://ericksuarez.dev/"
languageCode: en-us
title: "Erick Suárez"
theme:
  - PaperMod
DefaultContentLanguage: es
googleAnalytics: G-3P31T791CQ

menu:
  main:
    - identifier: about
      name: Sobre mi
      url: /about/
      weight: 1
    - identifier: buscar
      name: Buscar
      url: /search/
      weight: 10
    - identifier: categories
      name: Categorias
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

params:
  env: production
  keywords: [Blog, Portfolio, Backend, Desarrollo]
  author: "Erick Suárez"
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  comments: true

  homeInfoParams:
    Title: fmt.Println("Hola mundo 🤙")
    Content: "¡Hey! Soy Erick, Ingeniero de software [click para saber más](about), disfruto, entre otras cosas, aprender cada día algo nuevo y compartirlo. Ojalá encuentres útil alguno de los post que con gusto estaré actualizando, siéntete libre de contactarme por alguna de mis redes"

  socialIcons:
    - name: github
      url: "https://github.com/esvarez"
    - name: twitter
      url: "https://twitter.com/esuarezdev"
    - name: linkedin
      url: "https://www.linkedin.com/in/erick-su%C3%A1rez-zavala-317485145/"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

languages:
  es:
    languageName: "Español"
    weight: 1
  en:
    languageName: ":en:"
    languageAltTitle: English
    weight: 2
    menu:
      main:
        - identifier: about
          name: About
          url: /about/
          weight: 1
        - identifier: search
          name: Search
          url: /search/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
    params:
      homeInfoParams:
        Title: fmt.Println("Hello world 🤙")
        Content: "¡Hey! I'm Erick, a Software engineer [click to know more](about), I enjoy learning new things and sharing them. I hope you find useful my posts, feel free to reach me out on any of my social networks to collaborate, ask anything or just say hello"

taxonomies:
  category: categories
  tag: tags
  langs: langs

outputs:
  home:
    - HTML
    - RSS
    - JSON
